# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-24 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_auto_20170524_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, default=b'', max_length=128, verbose_name='Payment method'),
        ),
    ]
